version: "2"

linters:
  enable:
    # ==========================================================================
    # CONCURRENCY & RACE CONDITIONS
    # ==========================================================================
    # Context misuse (common source of races and deadlocks)
    - contextcheck      # Non-inherited context detection
    - containedctx      # Context in struct fields (anti-pattern)
    - noctx             # HTTP requests without context
    - fatcontext        # Nested contexts in loops

    # ==========================================================================
    # MEMORY SAFETY & RESOURCE MANAGEMENT
    # ==========================================================================
    # Resource leaks (can lead to exhaustion, pseudo-deadlocks)
    - bodyclose         # HTTP response body not closed
    - sqlclosecheck     # SQL rows/stmt not closed
    - rowserrcheck      # Rows.Err not checked
    - errcheck          # Unchecked errors (can hide resource leaks)

    # Nil/null safety
    - nilerr            # Returns nil even when err != nil
    - nilnil            # Simultaneous nil error and nil value
    - nilnesserr        # err != nil check but returns different nil error
    - forcetypeassert   # Forced type assertions (can panic)

    # ==========================================================================
    # SECURITY (TOCTOU, injection, etc.)
    # ==========================================================================
    - gosec             # Security problems (G101-G601)
    - bidichk           # Dangerous unicode sequences (trojan source)

    # ==========================================================================
    # CORRECTNESS - REAL BUGS
    # ==========================================================================
    - staticcheck       # Comprehensive static analysis (SA*/S*/ST*/QF*)
    - govet             # Go vet checks (copylocks, printf, etc.)
    - gocritic          # Bug/performance/style checks
    - errorlint         # Error wrapping issues (Go 1.13+)
    - durationcheck     # Multiplied durations
    - makezero          # Slice with non-zero length (append bugs)
    - reassign          # Package variable reassignment
    - spancheck         # OpenTelemetry span mistakes
    - asasalint         # Pass []any as any in variadic

    # ==========================================================================
    # PERFORMANCE (can cause timing issues, resource exhaustion)
    # ==========================================================================
    - prealloc          # Slice preallocation
    - ineffassign       # Ineffective assignments
    - unconvert         # Unnecessary conversions
    - perfsprint        # Faster fmt alternatives
    - copyloopvar       # Loop variable copies (Go 1.22 fixed but still useful)

    # ==========================================================================
    # CODE QUALITY (prevents future bugs)
    # ==========================================================================
    - sloglint          # Structured logging consistency
    - musttag           # Struct tags in marshaled structs
    - predeclared       # Shadowing predeclared identifiers
    - mirror            # Wrong bytes/strings patterns

  disable-all: true

linters-settings:
  # ===========================================================================
  # GOVET - Extended checks for concurrency bugs
  # ===========================================================================
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy, micro-optimization
    settings:
      shadow:
        strict: true    # Strict shadowing detection

  # ===========================================================================
  # GOSEC - Security analysis
  # ===========================================================================
  gosec:
    excludes: []  # Enable all rules
    severity: low
    confidence: low
    config:
      global:
        # Audit mode - report all issues
        audit: true
      # G101: Hardcoded credentials
      G101:
        pattern: "(?i)(password|secret|key|token|apikey|api_key|auth)"
      # G306: Poor file permissions
      G306:
        mode: "0600"

  # ===========================================================================
  # GOCRITIC - Comprehensive diagnostics
  # ===========================================================================
  gocritic:
    enabled-tags:
      - diagnostic      # Possible bugs
      - performance     # Performance issues
      - style           # Style issues that may indicate bugs
      - opinionated     # Opinionated but useful
      - experimental    # Experimental checks
    disabled-checks:
      - whyNoLint       # Too noisy
      - hugeParam       # Often intentional
    settings:
      rangeValCopy:
        sizeThreshold: 128
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false

  # ===========================================================================
  # STATICCHECK - Enable all checks
  # ===========================================================================
  staticcheck:
    checks:
      - all
      - -SA1019  # Deprecated (too noisy during transitions)

  # ===========================================================================
  # ERRCHECK - Type assertions and more
  # ===========================================================================
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy
      - (io.Closer).Close
      - (*os.File).Close

  # ===========================================================================
  # CONTEXTCHECK - Context propagation
  # ===========================================================================
  contextcheck:
    disableFact: false

  # ===========================================================================
  # PREALLOC
  # ===========================================================================
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  # ===========================================================================
  # PERFSPRINT
  # ===========================================================================
  perfsprint:
    int-conversion: true
    err-error: true
    errorf: true
    sprintf1: true
    strconcat: true

  # ===========================================================================
  # MUSTTAG - Struct tags
  # ===========================================================================
  musttag:
    functions:
      - name: json.Marshal
      - name: json.Unmarshal
      - name: encoding/json.Marshal
      - name: encoding/json.Unmarshal

issues:
  # Show all issues
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude patterns
  exclude-rules:
    # Generated files
    - path: '\.pb\.go$'
      linters: [all]
    - path: '_grpc\.pb\.go$'
      linters: [all]

    # Test files - relax some checks
    - path: '_test\.go$'
      linters:
        - errcheck
        - gosec
        - forcetypeassert
        - contextcheck

    # Allow unchecked Close() in defer
    - source: 'defer .+\.Close\(\)'
      linters: [errcheck]

    # Old build tags (batch fix later)
    - text: "buildtag:.+build line is no longer needed"
      linters: [govet]

  # Include test files in analysis
  exclude-dirs:
    - vendor
    - third_party
    - testdata

run:
  timeout: 10m
  tests: true
  build-tags:
    - integration

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
